<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function upgrade_status_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'upgrade_status.report') {
    return '<p>' . t('Analyze your site\'s Drupal 9 readiness. Run the report to find out if there are detectable compatibility errors with the modules and themes installed on your site. <a href=":prepare">Read more about preparing your site for Drupal 9</a>.', [':prepare' => 'https://www.drupal.org/documentation/9#preparefor9']) . '</p>';
  }
}

/**
 * Implements hook_rebuild().
 */
function upgrade_status_rebuild() {
  \Drupal::state()->delete('upgrade_status.number_of_jobs');
  \Drupal::state()->delete('upgrade_status.last_scan');
}
