<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function upgrade_status_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'upgrade_status.report') {
    return '<p>' . t('Analyze your site\'s Drupal 9 readiness. Run the report to find out if there are detectable compatibility errors with the modules and themes installed on your site. <a href=":prepare">Read more about preparing your site for Drupal 9</a>.', [':prepare' => 'https://www.drupal.org/docs/9/how-to-prepare-your-drupal-7-or-8-site-for-drupal-9/prepare-a-drupal-8-site-for-drupal-9']) . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function upgrade_status_theme($existing, $type, $theme, $path) {
  return [
    'full_export' => [
      'variables' => [
        'projects' => [],
        'date' => '',
      ],
    ],
    'single_export' => [
      'variables' => [
        'project' => [],
        'date' => '',
      ],
    ],
  ];
}

function template_preprocess_full_export(&$variables) {
  $projects = $variables['projects'];

  foreach ($projects['custom'] as $key => $project) {
    $variables['projects']['custom'][$key]['name'] = $projects['custom'][$key]['#title'];
  }

  foreach ($projects['contrib'] as $key => $project) {
    $variables['projects']['contrib'][$key]['name'] = $projects['contrib'][$key]['#title'];
  }
}

