<?php

/**
 * @file
 * Install, update, and uninstall functions for the Upgrade Status module.
 */

/**
 * Implements hook_uninstall().
 */
function upgrade_status_uninstall() {
  \Drupal::state()->delete('upgrade_status.number_of_jobs');
  \Drupal::state()->delete('upgrade_status.last_scan');
  \Drupal::keyValue('upgrade_status_scan_results')->deleteAll();

  $queue = \Drupal::queue('upgrade_status_deprecation_worker');
  $queue->deleteQueue();
}
