<?php

/**
 * Tests function deprecation detection.
 *
 * @deprecated in drupal:8.6.0 and is removed from drupal:9.0.0. Use the
 *   replacement instead.
 */
function upgrade_status_test_contrib_error_function() {
  @trigger_error("upgrade_status_test_contrib_error_function() is deprecated in Drupal 8.6.0 and will be removed before Drupal 9.0.0. Use the replacement instead. See LINK", E_USER_DEPRECATED);
}
